### ISSUE TITLE
spring run app.groovy  does not work

### ISSUE THREAD

**Issue by epiphyllum** [learning-spring-boot/learning-spring-boot-code#2]
 ~/workspace/learning-spring-boot-code/ch1/ [master] spring run app.groovy
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.springframework.boot.cli.app.SpringApplicationLauncher.launch(SpringApplicationLauncher.java:65)
    at org.springframework.boot.cli.command.run.SpringApplicationRunner$RunThread.run(SpringApplicationRunner.java:148)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
    at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:161)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at org.springframework.boot.cli.compiler.ExtendedGroovyClassLoader.findClass(ExtendedGroovyClassLoader.java:84)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
    at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
    at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775)
    ... 7 more

**Comment by gregturn** [comment]
@epiphyllum Can you do me a favor and show the version of Spring Boot CLI you are using? I wrote the book against 1.1.6.RELEASE and there may have been some changes since then.

**Comment by epiphyllum** [comment]
 ~/ spring --version
Spring CLI v1.2.6.RELEASE
 ~/

**Comment by gregturn** [comment]
@epiphyllum I'm sorry I haven't gotten back to you sooner.

I went and installed a copy of Spring Boot CLI 1.2.6.RELEASE using [sdkman](http://sdkman.io/) and that code worked perfectly.

```
gturnquist$ cd ch1
gturnquist$ spring run app.groovy 
Maven settings decryption failed. Some Maven repositories may be inaccessible
Resolving dependencies.........................

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.6.RELEASE)

2015-10-29 11:15:29.838  INFO 91344 --- [       runner-0] o.s.boot.SpringApplication               : Starting application on retina with PID 91344 (/Users/gturnquist/.m2/repository/org/springframework/boot/spring-boot/1.2.6.RELEASE/spring-boot-1.2.6.RELEASE.jar started by gturnquist in /Users/gturnquist/Dropbox/Greg/learning-spring-boot-code/ch1)
2015-10-29 11:15:29.957  INFO 91344 --- [       runner-0] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@686e02fa: startup date [Thu Oct 29 11:15:29 CDT 2015]; root of context hierarchy
2015-10-29 11:15:30.140  WARN 91344 --- [       runner-0] .i.s.PathMatchingResourcePatternResolver : Skipping [/Users/gturnquist/.sdkman/springboot/1.2.6.RELEASE/lib/bcpkix-jdk15on-1.47.jar] because it does not denote a directory
2015-10-29 11:15:30.140  WARN 91344 --- [       runner-0] .i.s.PathMatchingResourcePatternResolver : Skipping [/Users/gturnquist/.sdkman/springboot/1.2.6.RELEASE/lib/bcprov-jdk15on-1.47.jar] because it does not denote a directory
2015-10-29 11:15:30.140  WARN 91344 --- [       runner-0] .i.s.PathMatchingResourcePatternResolver : Skipping [/Users/gturnquist/.sdkman/springboot/1.2.6.RELEASE/lib/commons-logging-1.2.jar] because it does not denote a directory
2015-10-29 11:15:30.140  WARN 91344 --- [       runner-0] .i.s.PathMatchingResourcePatternResolver : Skipping [/Users/gturnquist/.sdkman/springboot/1.2.6.RELEASE/lib/spring-security-crypto-3.2.8.RELEASE.jar] because it does not denote a directory
2015-10-29 11:15:30.140  WARN 91344 --- [       runner-0] .i.s.PathMatchingResourcePatternResolver : Skipping [/Users/gturnquist/.sdkman/springboot/1.2.6.RELEASE/lib/spring-security-rsa-1.0.1.RELEASE.jar] because it does not denote a directory
2015-10-29 11:15:30.442  INFO 91344 --- [       runner-0] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver': replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2015-10-29 11:15:30.974  INFO 91344 --- [       runner-0] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2015-10-29 11:15:31.096  INFO 91344 --- [       runner-0] o.apache.catalina.core.StandardService   : Starting service Tomcat
2015-10-29 11:15:31.098  INFO 91344 --- [       runner-0] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.26
2015-10-29 11:15:31.160  INFO 91344 --- [ost-startStop-1] org.apache.catalina.loader.WebappLoader  : Unknown loader org.springframework.boot.cli.compiler.ExtendedGroovyClassLoader$DefaultScopeParentClassLoader@8aacf67 class org.springframework.boot.cli.compiler.ExtendedGroovyClassLoader$DefaultScopeParentClassLoader
2015-10-29 11:15:31.178  INFO 91344 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2015-10-29 11:15:31.179  INFO 91344 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1222 ms
2015-10-29 11:15:31.731  INFO 91344 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2015-10-29 11:15:31.735  INFO 91344 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2015-10-29 11:15:31.736  INFO 91344 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2015-10-29 11:15:31.896  INFO 91344 --- [       runner-0] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@686e02fa: startup date [Thu Oct 29 11:15:29 CDT 2015]; root of context hierarchy
2015-10-29 11:15:31.936  INFO 91344 --- [       runner-0] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/]}" onto public java.lang.Object App.home()
2015-10-29 11:15:31.937  INFO 91344 --- [       runner-0] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2015-10-29 11:15:31.937  INFO 91344 --- [       runner-0] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest)
2015-10-29 11:15:31.941  INFO 91344 --- [       runner-0] o.s.w.s.c.a.WebMvcConfigurerAdapter      : Adding welcome page: file:/Users/gturnquist/Dropbox/Greg/learning-spring-boot-code/ch1/static/index.html
2015-10-29 11:15:31.952  INFO 91344 --- [       runner-0] o.s.w.s.handler.SimpleUrlHandlerMapping  : Root mapping to handler of type [class org.springframework.web.servlet.mvc.ParameterizableViewController]
2015-10-29 11:15:31.960  INFO 91344 --- [       runner-0] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-10-29 11:15:31.960  INFO 91344 --- [       runner-0] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
```

I wonder if you need to clean out your maven local repo and try again. Even though there is an updated code base, the script you are trying to run hasn't changed at all.
